# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
- task: SynopsysDetectTask@6
  inputs:
    BlackDuckService: 'blackduck_server'
    DetectVersion: 'latest'
    DetectArguments: '--blackduck.url=https://ec2-3-90-44-94.compute-1.amazonaws.com/ --blackduck.trust.cert=true --detect.cleanup=false --detect.diagnostic=true --detect.project.name=pipeline_ado --blackduck.api.token=MTFkYzY4MjItOTIwMy00ZmMwLWE3OTQtMjI2MzIwMmU5MWFkOjExYWNlMzIzLTI2MjMtNDc1Zi04NTJiLTNhMjQ0YTI3ZjkwYg=='
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
