# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
- task: SynopsysDetectTask@6
  inputs:
    BlackDuckService: 'blackduck_server'
    DetectVersion: 'latest'
    DetectArguments: '--blackduck.url=https://ec2-3-222-251-139.compute-1.amazonaws.com/ --blackduck.trust.cert=true --detect.cleanup=false --detect.diagnostic=true --detect.project.name=pipeline_ado --blackduck.api.token=Y2JkZWVkZjUtNmU1NS00NTZiLWFjYjctNjM0MThmZWZlYjliOjg1NDVmOTEzLTJmNzAtNDliMS05ZjVkLTI0ZTU1ZDk0NmZkMg=='
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
